""":command:`filoma` standalone commands — demo, ask, dedup, audit helpers, interactive shell."""

import shutil
import tempfile
import webbrowser
from pathlib import Path
from typing import List, Optional

import typer
from loguru import logger
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn

from ._app import app, console


@app.command("ask")
def ask_command(
    prompt: List[str] = typer.Argument(..., help="Your question, e.g. 'how many .py files are here?'"),
    path: Optional[str] = typer.Option(None, "--path", "-p", help="Directory the agent works against (defaults to cwd)."),
    model: Optional[str] = typer.Option(None, "--model", "-m", help="AI model to use."),
) -> None:
    """One-shot Filaraki question — prints the answer and exits.

    Mirrors the Python helper ``filoma.ask(...)``. Useful for scripts and
    quick one-liners; for back-and-forth use ``filoma chat`` instead.

    Example:
        filoma ask how many python files are here?
        filoma ask "audit this dataset" --path ./images

    """
    import filoma as flm

    question = " ".join(prompt).strip()
    if not question:
        console.print("[red]No question provided.[/red]")
        raise typer.Exit(code=1)

    result = flm.ask(question, path=path, model=model)
    output = getattr(result, "output", result)
    console.print(output)


@app.command("setup")
def setup_command() -> None:
    """Launch the interactive Filaraki setup wizard.

    Configures provider (Ollama / Mistral / Gemini / OpenAI-compatible) and
    writes a ``.env`` file in the current directory. Equivalent to running
    the bundled ``setup_env.sh`` script directly.
    """
    import os
    import subprocess
    import sys
    from importlib.resources import as_file, files

    bash = shutil.which("bash")
    if bash is None:
        console.print("[red]This wizard requires `bash`.[/red] On Windows, run it from WSL or Git Bash, or open the file manually:")
        console.print("    src/filoma/scripts/setup_env.sh")
        raise typer.Exit(code=1)

    try:
        script_resource = files("filoma.scripts").joinpath("setup_env.sh")
    except (ModuleNotFoundError, FileNotFoundError) as exc:
        console.print(f"[red]Could not locate setup script: {exc}[/red]")
        raise typer.Exit(code=1) from exc

    with as_file(script_resource) as script_path:
        if not script_path.exists():
            console.print(f"[red]Setup script not found at {script_path}[/red]")
            raise typer.Exit(code=1)
        result = subprocess.run(
            [bash, str(script_path)],
            cwd=os.getcwd(),
            check=False,
        )
    if result.returncode != 0:
        sys.exit(result.returncode)


@app.command("chat")
def chat(
    model: Optional[str] = typer.Option(None, "--model", "-m", help="AI model to use"),
) -> None:
    """Start an interactive Filaraki chat (shorthand for ``filoma filaraki chat``)."""
    from filoma.filaraki.cli import chat as start_chat

    start_chat(model=model)


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------


def _make_demo_fixture(root: Path) -> None:
    """Populate ``root`` with a small synthetic dataset for ``filoma demo``.

    Creates ~12 files including planted duplicate pairs and one zero-byte
    file so every audit stage (probe, dedup, corruption) has something to
    show. Kept tiny on purpose — the whole demo runs in well under a second.
    """
    (root / "train").mkdir()
    (root / "valid").mkdir()
    (root / "notes").mkdir()

    (root / "train" / "a.txt").write_text("alpha sample one\n")
    (root / "train" / "b.txt").write_text("beta sample two\n")
    (root / "train" / "c.txt").write_text("gamma sample three\n")
    (root / "valid" / "d.txt").write_text("delta sample four\n")
    (root / "valid" / "e.txt").write_text("epsilon sample five\n")

    duplicate_payload = "duplicated content used to demonstrate dedup\n"
    (root / "train" / "dup1.txt").write_text(duplicate_payload)
    (root / "valid" / "dup1_copy.txt").write_text(duplicate_payload)

    other_dup = '{"label": "cat", "id": 42}\n'
    (root / "train" / "meta.json").write_text(other_dup)
    (root / "valid" / "meta_copy.json").write_text(other_dup)

    (root / "notes" / "README.md").write_text("# Demo dataset\n\nGenerated by `filoma demo`.\n")
    (root / "notes" / "empty.log").write_bytes(b"")


def _can_open_browser() -> bool:
    """Heuristic: only attempt a real GUI open when one is likely to work.

    Avoids the WSL/headless case where ``webbrowser.open`` returns True
    but ``xdg-open`` then fails to find any browser.
    """
    import os
    import platform
    import sys

    system = platform.system()
    if system in ("Darwin", "Windows"):
        return True
    if sys.platform.startswith("win"):
        return True
    if os.environ.get("WSL_DISTRO_NAME") or "microsoft" in platform.release().lower():
        return False
    return bool(os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY") or os.environ.get("BROWSER"))


@app.command()
def demo() -> None:
    """Run a 60-second end-to-end demo on a tiny synthetic dataset.

    Generates a small fixture, runs probe -> enrich -> quality scan -> dedup,
    exports a self-contained HTML audit report, and opens it in your
    browser. No flags, no setup, no network.
    """
    from filoma import Dataset

    report_dest = Path(tempfile.gettempdir()) / "filoma_demo_audit.html"
    report_url = f"file://{report_dest}"

    logger.disable("filoma")
    try:
        with tempfile.TemporaryDirectory(prefix="filoma_demo_") as tmpdir:
            root = Path(tmpdir)
            console.print(
                Panel.fit(
                    "[bold green]\U0001f343 Filoma demo[/bold green]\n[dim]Generating a tiny dataset and running the full pipeline...[/dim]",
                    border_style="green",
                )
            )

            _make_demo_fixture(root)
            console.print(f"[dim]Sample dataset:[/dim] {root}")

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                transient=True,
                console=console,
            ) as progress:
                progress.add_task("Snapshotting...", total=None)
                ds = Dataset(root).snap(mode="fast")

                progress.add_task("Building enriched DataFrame...", total=None)
                df = ds.to_dataframe()

                progress.add_task("Running quality scan...", total=None)
                verifier = ds.run_quality_scan()

                progress.add_task("Finding duplicates...", total=None)
                dupes = ds.dedup()

            console.print(f"\n[bold]Files scanned:[/bold] {df.df.height}")
            console.print("\n[bold blue]Quality summary[/bold blue]")
            verifier.print_summary()

            console.print("\n[bold blue]Duplicate scan[/bold blue]")
            for category in ("exact", "text", "image"):
                groups = (dupes or {}).get(category, [])
                if groups:
                    console.print(f"[yellow]{category.capitalize()} duplicates ({len(groups)} groups):[/yellow]")
                    for i, group in enumerate(groups, start=1):
                        console.print(f"  Group {i}:")
                        for file_path in group:
                            console.print(f"    \u2022 {file_path}")
                else:
                    console.print(f"[dim]No {category} duplicates found.[/dim]")

            console.print("\n[bold blue]Generating HTML audit report...[/bold blue]")
            from filoma.filaraki.tools import audit_dataset

            tmp_report = root / "audit.html"
            audit_dataset(
                None,  # type: ignore[arg-type]
                str(root),
                mode="concise",
                show_evidence=True,
                export_path=str(tmp_report),
                export_format="html",
            )
            shutil.copyfile(tmp_report, report_dest)

        console.print()
        console.print(
            Panel.fit(
                f"[bold green]\u2705 Audit report ready[/bold green]\n[bold]{report_url}[/bold]",
                border_style="green",
            )
        )

        if _can_open_browser():
            try:
                webbrowser.open(report_url)
            except Exception:
                pass
        else:
            console.print("[dim]No GUI browser detected \u2014 open the file:// URL above to view the report.[/dim]")

    except KeyboardInterrupt:
        console.print("\n[yellow]Demo cancelled.[/yellow]")
        raise typer.Exit(130)
    except Exception as e:
        console.print(f"[red]Demo failed: {e}[/red]")
        raise typer.Exit(1)
    finally:
        logger.enable("filoma")


# ---------------------------------------------------------------------------
# Integrity / quality / dedup commands
# ---------------------------------------------------------------------------


@app.command()
def verify(
    reference: str = typer.Argument(..., help="Path to reference snapshot or manifest file"),
    target: str = typer.Option(..., "--target", "-t", help="Target directory for integrity check"),
) -> None:
    """Verify dataset integrity using snapshots or manifests."""
    from filoma.core.verifier import verify_dataset

    console.print(f"[bold blue]Checking integrity of {target} against {reference}...[/bold blue]")
    try:
        results = verify_dataset(reference, target_path=target)
        console.print("[green]\u2705 Integrity check complete.[/green]")
        console.print(results)
    except Exception as e:
        console.print(f"[red]Error during verification: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def quality(
    path: str = typer.Argument(..., help="Dataset path for quality check"),
) -> None:
    """Run data quality analysis on a dataset."""
    from filoma.core.verifier import DatasetVerifier

    console.print(f"[bold blue]Running quality checks on {path}...[/bold blue]")
    try:
        verifier = DatasetVerifier(path)
        verifier.run_all()
        verifier.print_summary()
    except Exception as e:
        console.print(f"[red]Error during quality checks: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def dedup(
    paths: List[str] = typer.Argument(..., help="Path(s) to check for duplicates"),
    cross_dir: bool = typer.Option(False, "--cross-dir", help="Only check for duplicates across provided paths"),
) -> None:
    """Find and report duplicate files in one or more directories."""
    import filoma

    console.print(f"[bold blue]Checking for duplicates in {', '.join(paths)}...[/bold blue]")
    try:
        combined_dfs = [filoma.probe_to_df(p) for p in paths]
        combined_df = combined_dfs[0]
        for df in combined_dfs[1:]:
            combined_df = combined_df.vstack(df.to_polars())

        df = filoma.DataFrame(combined_df)
        cross_dir_paths = paths if cross_dir else None
        dupes = df.evaluate_duplicates(show_table=True, cross_dir_paths=cross_dir_paths)

        for category in ["exact", "text", "image"]:
            groups = dupes.get(category, [])
            if groups:
                console.print(f"\n[bold yellow]{category.capitalize()} duplicates ({len(groups)} groups):[/bold yellow]")
                for i, group in enumerate(groups):
                    console.print(f"Group {i + 1}:")
                    for file_path in group:
                        console.print(f"  \u2022 {file_path}")
            else:
                console.print(f"\n[dim]No {category} duplicates found.[/dim]")
    except Exception as e:
        console.print(f"[red]Error during duplicate check: {e}[/red]")
        raise typer.Exit(1)


@app.command()
def main(path: Optional[str] = typer.Argument(None, help="Starting directory (defaults to current directory)")) -> None:
    """Interactive filesystem profiling and analysis tool.

    Navigate directories with arrow keys and probe files/folders using filoma's analysis functions.
    """
    from ._interactive import browse_and_probe

    try:
        if path is not None:
            start_dir = Path(path).resolve()
            if not start_dir.exists():
                console.print(f"[red]Error: Directory '{path}' does not exist[/red]")
                raise typer.Exit(1)
            if not start_dir.is_dir():
                console.print(f"[red]Error: '{path}' is not a directory[/red]")
                raise typer.Exit(1)
        else:
            start_dir = Path.cwd()

        browse_and_probe(start_dir)

    except KeyboardInterrupt:
        console.print("\n[yellow]Goodbye! \U0001f44b[/yellow]")
    except Exception as e:
        console.print(f"\n[red]Unexpected error: {e}[/red]")
        raise typer.Exit(1)
